jrs_blog:
    resource: "@JRsBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

test_hello:
    resource: "@JRsTestBundle/Resources/config/routing.yml"
    prefix:   /

